//! Phase 5.3 LexPrime Rust 核心 — build script
//!
//! 11/15 W22 phase5-rust-build-fix 工作: 添加 build.rs 验证 Cargo 多 target 路径解析.
//!
//! # W22 build-script bug 修复背景
//!
//! W21 启动时未添加 build.rs, Cargo 默认从包根 `build.rs` 自动发现. W22 显式
//! 添加本文件, 一来验证 Cargo 1.96 build-script 路径解析在 Windows + Linux 跨平台
//! 下都能正确解析 (CARGO_MANIFEST_DIR 在 build.rs 执行时是 cargo 注入的标准环境
//! 变量, 不是依赖路径), 二来给 Phase 5.3 注入编译时常量 (BUILD_TIMESTAMP / TARGET / PROFILE),
//! 供 lib.rs 的 `manifest()` / `health()` handler 展示.
//!
//! # Windows Defender build-script 拦截说明
//!
//! 在 Windows 上, Defender 实时保护会短暂拦截 cargo 生成的 build-script 可执行文件
//! (`build-script-build.exe`), 表现为 `os error 5 拒绝访问 (never executed)`.
//! 这是 Defender 扫描延迟导致, 多次重试 / CARGO_BUILD_JOBS=1 通常可缓解.
//! 临时解决: 用 admin 运行 `Set-MpPreference -DisableRealtimeMonitoring $true`.
//! 永久解决: 在 Defender exclusion 加入 CARGO_TARGET_DIR 路径.
//!
//! 参考: https://github.com/rust-lang/cargo/issues/8718 (类似报告)
//!
//! # Multi-target 路径正确性
//!
//! `CARGO_MANIFEST_DIR` 始终指向当前 build 的 crate manifest 目录, 在多 target
//! (x86_64-pc-windows-msvc / x86_64-pc-windows-gnullvm / x86_64-unknown-linux-gnu)
//! 交叉编译时也保持正确, 不需要硬编码路径.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let target = env::var("TARGET").unwrap_or_else(|_| "unknown".into());
    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".into());
    let host = env::var("HOST").unwrap_or_else(|_| "unknown".into());

    // Build timestamp (Unix epoch seconds)
    let build_ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    // 写入 out_dir 让 rustc 编译进 binary
    // 使用 raw string + escape_default 处理 Windows 中文路径 (元枢法智) 里
    // 反斜杠 \ 会被 format! 视为 escape 字符 (\u 等), 必须先 escape_default()
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let meta_path = out_dir.join("build_metadata.rs");
    let manifest_escaped = manifest_dir.escape_default().to_string();
    let meta_content = format!(
        "// Auto-generated by build.rs at compile time.\n\
         pub const BUILD_TIMESTAMP: u64 = {build_ts};\n\
         pub const BUILD_TARGET: &str = \"{target}\";\n\
         pub const BUILD_PROFILE: &str = \"{profile}\";\n\
         pub const BUILD_HOST: &str = \"{host}\";\n\
         pub const BUILD_MANIFEST_DIR: &str = \"{manifest_escaped}\";\n\
         pub const BUILD_TOOLCHAIN: &str = \"{toolchain}\";\n",
        toolchain = rustc_version().escape_default(),
    );
    fs::write(&meta_path, meta_content).expect("write build_metadata.rs");

    // 告诉 cargo rerun-if-changed (build.rs 改了才重新跑)
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=BUILD_TOOLCHAIN_OVERRIDE");

    // W22 防御性日志: 在编译期输出关键信息, 方便 e2e 验证 build-script 路径解析正确
    eprintln!(
        "[build.rs] manifest={} target={} profile={} ts={}",
        manifest_dir, target, profile, build_ts
    );
}

fn rustc_version() -> String {
    // 简单读 rustc 版本字符串 (不调 rustc --version, 避免 build.rs 二次 spawn)
    // 实际值由 build.rs 写入 BUILD_TOOLCHAIN 字符串, owner 可在 e2e 时替换
    env::var("RUSTC").unwrap_or_else(|_| "rustc".into())
}