"""Initial migration with indexes

Revision ID: 99ee6faf15ca
Revises: 
Create Date: 2026-07-03 06:19:58.981240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ee6faf15ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('subscription_tier', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_role_active', 'auth_users', ['role', 'is_active'], unique=False)
    op.create_index('idx_user_tier_active', 'auth_users', ['subscription_tier', 'is_active'], unique=False)
    op.create_index(op.f('ix_auth_users_created_at'), 'auth_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_is_2fa_enabled'), 'auth_users', ['is_2fa_enabled'], unique=False)
    op.create_index(op.f('ix_auth_users_is_active'), 'auth_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_auth_users_is_email_verified'), 'auth_users', ['is_email_verified'], unique=False)
    op.create_index(op.f('ix_auth_users_is_phone_verified'), 'auth_users', ['is_phone_verified'], unique=False)
    op.create_index(op.f('ix_auth_users_last_login_at'), 'auth_users', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_auth_users_locked_until'), 'auth_users', ['locked_until'], unique=False)
    op.create_index(op.f('ix_auth_users_phone'), 'auth_users', ['phone'], unique=True)
    op.create_index(op.f('ix_auth_users_role'), 'auth_users', ['role'], unique=False)
    op.create_index(op.f('ix_auth_users_subscription_tier'), 'auth_users', ['subscription_tier'], unique=False)
    op.create_index(op.f('ix_auth_users_updated_at'), 'auth_users', ['updated_at'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.String(length=128), nullable=True),
    sa.Column('case_name', sa.Text(), nullable=True),
    sa.Column('court', sa.String(length=256), nullable=True),
    sa.Column('case_type', sa.String(length=64), nullable=True),
    sa.Column('procedure', sa.String(length=64), nullable=True),
    sa.Column('judgment_date', sa.Date(), nullable=True),
    sa.Column('public_date', sa.Date(), nullable=True),
    sa.Column('parties', sa.Text(), nullable=True),
    sa.Column('cause', sa.String(length=128), nullable=True),
    sa.Column('cause_category', sa.String(length=64), nullable=True),
    sa.Column('cause_color', sa.String(length=16), nullable=True),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('full_text_plain', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('lex_score', sa.SmallInteger(), nullable=True),
    sa.Column('lex_tags', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cases_cause_category_year', 'cases', ['cause_category', 'year'], unique=False)
    op.create_index('idx_cases_region_cause', 'cases', ['region', 'cause'], unique=False)
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_cases_case_type'), 'cases', ['case_type'], unique=False)
    op.create_index(op.f('ix_cases_cause'), 'cases', ['cause'], unique=False)
    op.create_index(op.f('ix_cases_cause_category'), 'cases', ['cause_category'], unique=False)
    op.create_index(op.f('ix_cases_court'), 'cases', ['court'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_doc_id'), 'cases', ['doc_id'], unique=True)
    op.create_index(op.f('ix_cases_judgment_date'), 'cases', ['judgment_date'], unique=False)
    op.create_index(op.f('ix_cases_lex_score'), 'cases', ['lex_score'], unique=False)
    op.create_index(op.f('ix_cases_region'), 'cases', ['region'], unique=False)
    op.create_index(op.f('ix_cases_source'), 'cases', ['source'], unique=False)
    op.create_index(op.f('ix_cases_updated_at'), 'cases', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cases_year'), 'cases', ['year'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unified_id', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=False),
    sa.Column('company_type', sa.String(length=64), nullable=True),
    sa.Column('legal_rep', sa.String(length=64), nullable=True),
    sa.Column('registered_capital', sa.String(length=64), nullable=True),
    sa.Column('paid_capital', sa.String(length=64), nullable=True),
    sa.Column('establish_date', sa.Date(), nullable=True),
    sa.Column('business_status', sa.String(length=32), nullable=True),
    sa.Column('registered_address', sa.String(length=512), nullable=True),
    sa.Column('business_scope', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('is_zxgk', sa.Boolean(), nullable=False),
    sa.Column('is_dishonest', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_companies_region_industry', 'companies', ['region', 'industry'], unique=False)
    op.create_index('idx_companies_status_region', 'companies', ['business_status', 'region'], unique=False)
    op.create_index(op.f('ix_companies_business_status'), 'companies', ['business_status'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_is_dishonest'), 'companies', ['is_dishonest'], unique=False)
    op.create_index(op.f('ix_companies_is_zxgk'), 'companies', ['is_zxgk'], unique=False)
    op.create_index(op.f('ix_companies_legal_rep'), 'companies', ['legal_rep'], unique=False)
    op.create_index(op.f('ix_companies_region'), 'companies', ['region'], unique=False)
    op.create_index(op.f('ix_companies_unified_id'), 'companies', ['unified_id'], unique=True)
    op.create_index(op.f('ix_companies_updated_at'), 'companies', ['updated_at'], unique=False)
    op.create_table('crawler_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('items_inserted', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crawler_source_status', 'crawler_runs', ['source', 'status'], unique=False)
    op.create_index(op.f('ix_crawler_runs_finished_at'), 'crawler_runs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_crawler_runs_source'), 'crawler_runs', ['source'], unique=False)
    op.create_index(op.f('ix_crawler_runs_started_at'), 'crawler_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_crawler_runs_status'), 'crawler_runs', ['status'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lawyer_id', 'target_type', 'target_id', name='uq_favorite')
    )
    op.create_index(op.f('ix_favorites_created_at'), 'favorites', ['created_at'], unique=False)
    op.create_index(op.f('ix_favorites_lawyer_id'), 'favorites', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_favorites_target_id'), 'favorites', ['target_id'], unique=False)
    op.create_index(op.f('ix_favorites_target_type'), 'favorites', ['target_type'], unique=False)
    op.create_table('firms',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('unified_id', sa.String(length=64), nullable=True),
    sa.Column('license_no', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('firm_size', sa.String(length=16), nullable=False),
    sa.Column('subscription_tier', sa.String(length=16), nullable=False),
    sa.Column('subscription_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_no')
    )
    op.create_index(op.f('ix_firms_created_at'), 'firms', ['created_at'], unique=False)
    op.create_index(op.f('ix_firms_firm_size'), 'firms', ['firm_size'], unique=False)
    op.create_index(op.f('ix_firms_name'), 'firms', ['name'], unique=False)
    op.create_index(op.f('ix_firms_region'), 'firms', ['region'], unique=False)
    op.create_index(op.f('ix_firms_subscription_expires_at'), 'firms', ['subscription_expires_at'], unique=False)
    op.create_index(op.f('ix_firms_subscription_tier'), 'firms', ['subscription_tier'], unique=False)
    op.create_index(op.f('ix_firms_unified_id'), 'firms', ['unified_id'], unique=False)
    op.create_index(op.f('ix_firms_updated_at'), 'firms', ['updated_at'], unique=False)
    op.create_table('laws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('law_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('law_number', sa.String(length=128), nullable=True),
    sa.Column('law_type', sa.String(length=64), nullable=False),
    sa.Column('issuing_organ', sa.String(length=256), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('revised_from', sa.String(length=64), nullable=True),
    sa.Column('revised_to', sa.String(length=64), nullable=True),
    sa.Column('related_laws', sa.JSON(), nullable=True),
    sa.Column('related_cases_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laws_created_at'), 'laws', ['created_at'], unique=False)
    op.create_index(op.f('ix_laws_effective_date'), 'laws', ['effective_date'], unique=False)
    op.create_index(op.f('ix_laws_law_id'), 'laws', ['law_id'], unique=True)
    op.create_index(op.f('ix_laws_law_type'), 'laws', ['law_type'], unique=False)
    op.create_index(op.f('ix_laws_level'), 'laws', ['level'], unique=False)
    op.create_index(op.f('ix_laws_status'), 'laws', ['status'], unique=False)
    op.create_index(op.f('ix_laws_updated_at'), 'laws', ['updated_at'], unique=False)
    op.create_table('auth_email_verifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_verify_email_purpose', 'auth_email_verifications', ['email', 'purpose'], unique=False)
    op.create_index('idx_email_verify_user_purpose', 'auth_email_verifications', ['user_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_auth_email_verifications_consumed_at'), 'auth_email_verifications', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_auth_email_verifications_created_at'), 'auth_email_verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_email_verifications_email'), 'auth_email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_auth_email_verifications_expires_at'), 'auth_email_verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_email_verifications_purpose'), 'auth_email_verifications', ['purpose'], unique=False)
    op.create_index(op.f('ix_auth_email_verifications_revoked_at'), 'auth_email_verifications', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_email_verifications_token_hash'), 'auth_email_verifications', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_email_verifications_user_id'), 'auth_email_verifications', ['user_id'], unique=False)
    op.create_table('auth_lawyer_profiles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('license_no', sa.String(length=64), nullable=True),
    sa.Column('firm_id', sa.String(length=64), nullable=True),
    sa.Column('firm_role', sa.String(length=16), nullable=False),
    sa.Column('license_status', sa.String(length=16), nullable=False),
    sa.Column('license_image_url', sa.Text(), nullable=True),
    sa.Column('license_ocr_data', sa.JSON(), nullable=True),
    sa.Column('license_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license_reviewed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('license_reject_reason', sa.Text(), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['license_reviewed_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_firm_status', 'auth_lawyer_profiles', ['firm_id', 'license_status'], unique=False)
    op.create_index('idx_profile_license_status', 'auth_lawyer_profiles', ['license_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_created_at'), 'auth_lawyer_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_firm_id'), 'auth_lawyer_profiles', ['firm_id'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_firm_role'), 'auth_lawyer_profiles', ['firm_role'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_license_no'), 'auth_lawyer_profiles', ['license_no'], unique=True)
    op.create_index(op.f('ix_auth_lawyer_profiles_license_reviewed_at'), 'auth_lawyer_profiles', ['license_reviewed_at'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_license_reviewed_by'), 'auth_lawyer_profiles', ['license_reviewed_by'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_license_status'), 'auth_lawyer_profiles', ['license_status'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_license_submitted_at'), 'auth_lawyer_profiles', ['license_submitted_at'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_name'), 'auth_lawyer_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_region'), 'auth_lawyer_profiles', ['region'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_updated_at'), 'auth_lawyer_profiles', ['updated_at'], unique=False)
    op.create_index(op.f('ix_auth_lawyer_profiles_user_id'), 'auth_lawyer_profiles', ['user_id'], unique=True)
    op.create_table('auth_otp_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('sent_to', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('related_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_target_purpose', 'auth_otp_logs', ['target', 'purpose'], unique=False)
    op.create_index('idx_otp_user_purpose', 'auth_otp_logs', ['related_user_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_auth_otp_logs_consumed_at'), 'auth_otp_logs', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_auth_otp_logs_created_at'), 'auth_otp_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_otp_logs_expires_at'), 'auth_otp_logs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_otp_logs_purpose'), 'auth_otp_logs', ['purpose'], unique=False)
    op.create_index(op.f('ix_auth_otp_logs_related_user_id'), 'auth_otp_logs', ['related_user_id'], unique=False)
    op.create_index(op.f('ix_auth_otp_logs_sent_to'), 'auth_otp_logs', ['sent_to'], unique=False)
    op.create_index(op.f('ix_auth_otp_logs_target'), 'auth_otp_logs', ['target'], unique=False)
    op.create_index(op.f('ix_auth_otp_logs_target_type'), 'auth_otp_logs', ['target_type'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('device_info', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_expires_revoked', 'auth_tokens', ['expires_at', 'revoked_at'], unique=False)
    op.create_index('idx_token_user_revoked', 'auth_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_tokens_expires_at'), 'auth_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_tokens_issued_at'), 'auth_tokens', ['issued_at'], unique=False)
    op.create_index(op.f('ix_auth_tokens_last_used_at'), 'auth_tokens', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_auth_tokens_revoked_at'), 'auth_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_tokens_token_type'), 'auth_tokens', ['token_type'], unique=False)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('auth_totp_backup_codes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('code_prefix', sa.String(length=8), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_totp_backup_user', 'auth_totp_backup_codes', ['user_id'], unique=False)
    op.create_index('idx_totp_backup_user_consumed', 'auth_totp_backup_codes', ['user_id', 'consumed_at'], unique=False)
    op.create_index(op.f('ix_auth_totp_backup_codes_consumed_at'), 'auth_totp_backup_codes', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_auth_totp_backup_codes_created_at'), 'auth_totp_backup_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_totp_backup_codes_user_id'), 'auth_totp_backup_codes', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('firm_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('client_type', sa.String(length=16), nullable=False),
    sa.Column('id_number', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clients_firm_grade', 'clients', ['firm_id', 'grade'], unique=False)
    op.create_index('idx_clients_firm_type', 'clients', ['firm_id', 'client_type'], unique=False)
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_clients_client_type'), 'clients', ['client_type'], unique=False)
    op.create_index(op.f('ix_clients_created_at'), 'clients', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_firm_id'), 'clients', ['firm_id'], unique=False)
    op.create_index(op.f('ix_clients_grade'), 'clients', ['grade'], unique=False)
    op.create_index(op.f('ix_clients_id_number'), 'clients', ['id_number'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_index(op.f('ix_clients_updated_at'), 'clients', ['updated_at'], unique=False)
    op.create_table('lawyer_added_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lawyer_id', sa.String(length=64), nullable=False),
    sa.Column('firm_id', sa.String(length=64), nullable=True),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('cause', sa.String(length=128), nullable=True),
    sa.Column('cause_category', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('related_official_case_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_official_case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_added_cases_case_id'), 'lawyer_added_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_lawyer_added_cases_cause'), 'lawyer_added_cases', ['cause'], unique=False)
    op.create_index(op.f('ix_lawyer_added_cases_cause_category'), 'lawyer_added_cases', ['cause_category'], unique=False)
    op.create_index(op.f('ix_lawyer_added_cases_created_at'), 'lawyer_added_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_lawyer_added_cases_firm_id'), 'lawyer_added_cases', ['firm_id'], unique=False)
    op.create_index(op.f('ix_lawyer_added_cases_lawyer_id'), 'lawyer_added_cases', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_lawyer_added_cases_related_official_case_id'), 'lawyer_added_cases', ['related_official_case_id'], unique=False)
    op.create_index(op.f('ix_lawyer_added_cases_updated_at'), 'lawyer_added_cases', ['updated_at'], unique=False)
    op.create_index(op.f('ix_lawyer_added_cases_visibility'), 'lawyer_added_cases', ['visibility'], unique=False)
    op.create_table('lawyers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('firm_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('license_no', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lawyers_firm_active', 'lawyers', ['firm_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_lawyers_created_at'), 'lawyers', ['created_at'], unique=False)
    op.create_index(op.f('ix_lawyers_email'), 'lawyers', ['email'], unique=True)
    op.create_index(op.f('ix_lawyers_firm_id'), 'lawyers', ['firm_id'], unique=False)
    op.create_index(op.f('ix_lawyers_is_active'), 'lawyers', ['is_active'], unique=False)
    op.create_index(op.f('ix_lawyers_license_no'), 'lawyers', ['license_no'], unique=True)
    op.create_index(op.f('ix_lawyers_name'), 'lawyers', ['name'], unique=False)
    op.create_index(op.f('ix_lawyers_phone'), 'lawyers', ['phone'], unique=False)
    op.create_index(op.f('ix_lawyers_role'), 'lawyers', ['role'], unique=False)
    op.create_index(op.f('ix_lawyers_updated_at'), 'lawyers', ['updated_at'], unique=False)
    op.create_table('auth_license_review_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['auth_lawyer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_license_review_actor', 'auth_license_review_logs', ['actor_id', 'actor_type'], unique=False)
    op.create_index('idx_license_review_profile', 'auth_license_review_logs', ['profile_id'], unique=False)
    op.create_index('idx_license_review_status', 'auth_license_review_logs', ['from_status', 'to_status'], unique=False)
    op.create_index(op.f('ix_auth_license_review_logs_actor_id'), 'auth_license_review_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_auth_license_review_logs_actor_type'), 'auth_license_review_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_auth_license_review_logs_created_at'), 'auth_license_review_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_license_review_logs_from_status'), 'auth_license_review_logs', ['from_status'], unique=False)
    op.create_index(op.f('ix_auth_license_review_logs_profile_id'), 'auth_license_review_logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_auth_license_review_logs_to_status'), 'auth_license_review_logs', ['to_status'], unique=False)
    op.create_index(op.f('ix_auth_license_review_logs_user_id'), 'auth_license_review_logs', ['user_id'], unique=False)
    op.create_table('firm_case_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firm_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('case_title', sa.String(length=512), nullable=False),
    sa.Column('lawyer_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'lawyer_id', name='uq_case_lawyer')
    )
    op.create_index('idx_fca_firm_lawyer', 'firm_case_assignments', ['firm_id', 'lawyer_id'], unique=False)
    op.create_index(op.f('ix_firm_case_assignments_assigned_at'), 'firm_case_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_firm_case_assignments_case_id'), 'firm_case_assignments', ['case_id'], unique=False)
    op.create_index(op.f('ix_firm_case_assignments_firm_id'), 'firm_case_assignments', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firm_case_assignments_lawyer_id'), 'firm_case_assignments', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_firm_case_assignments_role'), 'firm_case_assignments', ['role'], unique=False)
    op.create_table('firm_time_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firm_id', sa.String(length=64), nullable=False),
    sa.Column('lawyer_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fte_firm_date', 'firm_time_entries', ['firm_id', 'entry_date'], unique=False)
    op.create_index('idx_fte_lawyer_date', 'firm_time_entries', ['lawyer_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_firm_time_entries_billable'), 'firm_time_entries', ['billable'], unique=False)
    op.create_index(op.f('ix_firm_time_entries_case_id'), 'firm_time_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_firm_time_entries_created_at'), 'firm_time_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_firm_time_entries_entry_date'), 'firm_time_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_firm_time_entries_firm_id'), 'firm_time_entries', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firm_time_entries_lawyer_id'), 'firm_time_entries', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_firm_time_entries_status'), 'firm_time_entries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_time_entries_status'), table_name='firm_time_entries')
    op.drop_index(op.f('ix_firm_time_entries_lawyer_id'), table_name='firm_time_entries')
    op.drop_index(op.f('ix_firm_time_entries_firm_id'), table_name='firm_time_entries')
    op.drop_index(op.f('ix_firm_time_entries_entry_date'), table_name='firm_time_entries')
    op.drop_index(op.f('ix_firm_time_entries_created_at'), table_name='firm_time_entries')
    op.drop_index(op.f('ix_firm_time_entries_case_id'), table_name='firm_time_entries')
    op.drop_index(op.f('ix_firm_time_entries_billable'), table_name='firm_time_entries')
    op.drop_index('idx_fte_lawyer_date', table_name='firm_time_entries')
    op.drop_index('idx_fte_firm_date', table_name='firm_time_entries')
    op.drop_table('firm_time_entries')
    op.drop_index(op.f('ix_firm_case_assignments_role'), table_name='firm_case_assignments')
    op.drop_index(op.f('ix_firm_case_assignments_lawyer_id'), table_name='firm_case_assignments')
    op.drop_index(op.f('ix_firm_case_assignments_firm_id'), table_name='firm_case_assignments')
    op.drop_index(op.f('ix_firm_case_assignments_case_id'), table_name='firm_case_assignments')
    op.drop_index(op.f('ix_firm_case_assignments_assigned_at'), table_name='firm_case_assignments')
    op.drop_index('idx_fca_firm_lawyer', table_name='firm_case_assignments')
    op.drop_table('firm_case_assignments')
    op.drop_index(op.f('ix_auth_license_review_logs_user_id'), table_name='auth_license_review_logs')
    op.drop_index(op.f('ix_auth_license_review_logs_to_status'), table_name='auth_license_review_logs')
    op.drop_index(op.f('ix_auth_license_review_logs_profile_id'), table_name='auth_license_review_logs')
    op.drop_index(op.f('ix_auth_license_review_logs_from_status'), table_name='auth_license_review_logs')
    op.drop_index(op.f('ix_auth_license_review_logs_created_at'), table_name='auth_license_review_logs')
    op.drop_index(op.f('ix_auth_license_review_logs_actor_type'), table_name='auth_license_review_logs')
    op.drop_index(op.f('ix_auth_license_review_logs_actor_id'), table_name='auth_license_review_logs')
    op.drop_index('idx_license_review_status', table_name='auth_license_review_logs')
    op.drop_index('idx_license_review_profile', table_name='auth_license_review_logs')
    op.drop_index('idx_license_review_actor', table_name='auth_license_review_logs')
    op.drop_table('auth_license_review_logs')
    op.drop_index(op.f('ix_lawyers_updated_at'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_role'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_phone'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_name'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_license_no'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_is_active'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_firm_id'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_email'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_created_at'), table_name='lawyers')
    op.drop_index('idx_lawyers_firm_active', table_name='lawyers')
    op.drop_table('lawyers')
    op.drop_index(op.f('ix_lawyer_added_cases_visibility'), table_name='lawyer_added_cases')
    op.drop_index(op.f('ix_lawyer_added_cases_updated_at'), table_name='lawyer_added_cases')
    op.drop_index(op.f('ix_lawyer_added_cases_related_official_case_id'), table_name='lawyer_added_cases')
    op.drop_index(op.f('ix_lawyer_added_cases_lawyer_id'), table_name='lawyer_added_cases')
    op.drop_index(op.f('ix_lawyer_added_cases_firm_id'), table_name='lawyer_added_cases')
    op.drop_index(op.f('ix_lawyer_added_cases_created_at'), table_name='lawyer_added_cases')
    op.drop_index(op.f('ix_lawyer_added_cases_cause_category'), table_name='lawyer_added_cases')
    op.drop_index(op.f('ix_lawyer_added_cases_cause'), table_name='lawyer_added_cases')
    op.drop_index(op.f('ix_lawyer_added_cases_case_id'), table_name='lawyer_added_cases')
    op.drop_table('lawyer_added_cases')
    op.drop_index(op.f('ix_clients_updated_at'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_grade'), table_name='clients')
    op.drop_index(op.f('ix_clients_firm_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_created_at'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_type'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_index('idx_clients_firm_type', table_name='clients')
    op.drop_index('idx_clients_firm_grade', table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_auth_totp_backup_codes_user_id'), table_name='auth_totp_backup_codes')
    op.drop_index(op.f('ix_auth_totp_backup_codes_created_at'), table_name='auth_totp_backup_codes')
    op.drop_index(op.f('ix_auth_totp_backup_codes_consumed_at'), table_name='auth_totp_backup_codes')
    op.drop_index('idx_totp_backup_user_consumed', table_name='auth_totp_backup_codes')
    op.drop_index('idx_totp_backup_user', table_name='auth_totp_backup_codes')
    op.drop_table('auth_totp_backup_codes')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_type'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_revoked_at'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_last_used_at'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_issued_at'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_expires_at'), table_name='auth_tokens')
    op.drop_index('idx_token_user_revoked', table_name='auth_tokens')
    op.drop_index('idx_token_expires_revoked', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_auth_otp_logs_target_type'), table_name='auth_otp_logs')
    op.drop_index(op.f('ix_auth_otp_logs_target'), table_name='auth_otp_logs')
    op.drop_index(op.f('ix_auth_otp_logs_sent_to'), table_name='auth_otp_logs')
    op.drop_index(op.f('ix_auth_otp_logs_related_user_id'), table_name='auth_otp_logs')
    op.drop_index(op.f('ix_auth_otp_logs_purpose'), table_name='auth_otp_logs')
    op.drop_index(op.f('ix_auth_otp_logs_expires_at'), table_name='auth_otp_logs')
    op.drop_index(op.f('ix_auth_otp_logs_created_at'), table_name='auth_otp_logs')
    op.drop_index(op.f('ix_auth_otp_logs_consumed_at'), table_name='auth_otp_logs')
    op.drop_index('idx_otp_user_purpose', table_name='auth_otp_logs')
    op.drop_index('idx_otp_target_purpose', table_name='auth_otp_logs')
    op.drop_table('auth_otp_logs')
    op.drop_index(op.f('ix_auth_lawyer_profiles_user_id'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_updated_at'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_region'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_name'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_license_submitted_at'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_license_status'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_license_reviewed_by'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_license_reviewed_at'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_license_no'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_firm_role'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_firm_id'), table_name='auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_lawyer_profiles_created_at'), table_name='auth_lawyer_profiles')
    op.drop_index('idx_profile_license_status', table_name='auth_lawyer_profiles')
    op.drop_index('idx_profile_firm_status', table_name='auth_lawyer_profiles')
    op.drop_table('auth_lawyer_profiles')
    op.drop_index(op.f('ix_auth_email_verifications_user_id'), table_name='auth_email_verifications')
    op.drop_index(op.f('ix_auth_email_verifications_token_hash'), table_name='auth_email_verifications')
    op.drop_index(op.f('ix_auth_email_verifications_revoked_at'), table_name='auth_email_verifications')
    op.drop_index(op.f('ix_auth_email_verifications_purpose'), table_name='auth_email_verifications')
    op.drop_index(op.f('ix_auth_email_verifications_expires_at'), table_name='auth_email_verifications')
    op.drop_index(op.f('ix_auth_email_verifications_email'), table_name='auth_email_verifications')
    op.drop_index(op.f('ix_auth_email_verifications_created_at'), table_name='auth_email_verifications')
    op.drop_index(op.f('ix_auth_email_verifications_consumed_at'), table_name='auth_email_verifications')
    op.drop_index('idx_email_verify_user_purpose', table_name='auth_email_verifications')
    op.drop_index('idx_email_verify_email_purpose', table_name='auth_email_verifications')
    op.drop_table('auth_email_verifications')
    op.drop_index(op.f('ix_laws_updated_at'), table_name='laws')
    op.drop_index(op.f('ix_laws_status'), table_name='laws')
    op.drop_index(op.f('ix_laws_level'), table_name='laws')
    op.drop_index(op.f('ix_laws_law_type'), table_name='laws')
    op.drop_index(op.f('ix_laws_law_id'), table_name='laws')
    op.drop_index(op.f('ix_laws_effective_date'), table_name='laws')
    op.drop_index(op.f('ix_laws_created_at'), table_name='laws')
    op.drop_table('laws')
    op.drop_index(op.f('ix_firms_updated_at'), table_name='firms')
    op.drop_index(op.f('ix_firms_unified_id'), table_name='firms')
    op.drop_index(op.f('ix_firms_subscription_tier'), table_name='firms')
    op.drop_index(op.f('ix_firms_subscription_expires_at'), table_name='firms')
    op.drop_index(op.f('ix_firms_region'), table_name='firms')
    op.drop_index(op.f('ix_firms_name'), table_name='firms')
    op.drop_index(op.f('ix_firms_firm_size'), table_name='firms')
    op.drop_index(op.f('ix_firms_created_at'), table_name='firms')
    op.drop_table('firms')
    op.drop_index(op.f('ix_favorites_target_type'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_target_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_lawyer_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_created_at'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_crawler_runs_status'), table_name='crawler_runs')
    op.drop_index(op.f('ix_crawler_runs_started_at'), table_name='crawler_runs')
    op.drop_index(op.f('ix_crawler_runs_source'), table_name='crawler_runs')
    op.drop_index(op.f('ix_crawler_runs_finished_at'), table_name='crawler_runs')
    op.drop_index('idx_crawler_source_status', table_name='crawler_runs')
    op.drop_table('crawler_runs')
    op.drop_index(op.f('ix_companies_updated_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_unified_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_region'), table_name='companies')
    op.drop_index(op.f('ix_companies_legal_rep'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_zxgk'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_dishonest'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_business_status'), table_name='companies')
    op.drop_index('idx_companies_status_region', table_name='companies')
    op.drop_index('idx_companies_region_industry', table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_cases_year'), table_name='cases')
    op.drop_index(op.f('ix_cases_updated_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_source'), table_name='cases')
    op.drop_index(op.f('ix_cases_region'), table_name='cases')
    op.drop_index(op.f('ix_cases_lex_score'), table_name='cases')
    op.drop_index(op.f('ix_cases_judgment_date'), table_name='cases')
    op.drop_index(op.f('ix_cases_doc_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_court'), table_name='cases')
    op.drop_index(op.f('ix_cases_cause_category'), table_name='cases')
    op.drop_index(op.f('ix_cases_cause'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_type'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_index('idx_cases_region_cause', table_name='cases')
    op.drop_index('idx_cases_cause_category_year', table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_auth_users_updated_at'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_subscription_tier'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_role'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_phone'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_locked_until'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_last_login_at'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_is_phone_verified'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_is_email_verified'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_is_active'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_is_2fa_enabled'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_created_at'), table_name='auth_users')
    op.drop_index('idx_user_tier_active', table_name='auth_users')
    op.drop_index('idx_user_role_active', table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###