const globals = require('globals');

module.exports = [
    {
        ignores: ['assets/js/iconify-icon.min.js']
    },
    {
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: 'script',
            globals: {
                ...globals.browser,
                ...globals.node,
                Utils: 'readonly',
                showToast: 'readonly',
                switchView: 'readonly',
                switchToList: 'readonly',
                switchToMemberCenter: 'readonly',
                setMobileTabActive: 'readonly',
                AppState: 'readonly',
                API: 'readonly',
                escapeHtml: 'readonly',
                Iconify: 'readonly',
                hljs: 'readonly',
                Chart: 'readonly',
                echarts: 'readonly',
                Vue: 'readonly',
                Auth: 'readonly',
                loadView: 'readonly',
                switchSidebarTab: 'readonly',
                setupOutsideClickClose: 'readonly',
                fixTemplateViewDOM: 'readonly',
                renderPersonalTemplates: 'readonly',
                renderScheduleList: 'readonly',
                filterScheduleByDate: 'readonly',
                setNotificationsFilter: 'readonly',
                initAttachmentList: 'readonly',
                initAttentionList: 'readonly',
                initArchive: 'readonly',
                initFirm: 'readonly',
                initOrders: 'readonly',
                switchDynamicsView: 'readonly',
                initCaseDynamics: 'readonly',
                initCompaniesDb: 'readonly',
                initCasesDb: 'readonly',
                initZhixing: 'readonly',
                initLawsDb: 'readonly',
                initDeadlineView: 'readonly',
                initAIDocView: 'readonly',
                initCaseProgress: 'readonly',
                updateTodayScheduleBadge: 'readonly',
                renderTodayScheduleDateControls: 'readonly',
                renderTodaySchedule: 'readonly',
                _knowledgeSearch: 'writable',
                _knowledgeType: 'writable',
                _officialCategory: 'writable',
                _officialType: 'writable',
                _personalSortOrder: 'writable',
                addDynamicFile: 'readonly',
                applyKnowledgeFilter: 'readonly',
                caseCurrentPage: 'writable',
                closeAddEvidenceCatalogModal: 'readonly',
                currentDetailScheduleId: 'writable',
                currentEditSection: 'writable',
                getAllJudicialPoints: 'readonly',
                getFutureDate: 'readonly',
                getJudicialCauses: 'readonly',
                getJudicialPointById: 'readonly',
                getTodayDate: 'readonly',
                isDevMode: 'readonly',
                openCaseAnalysis: 'readonly',
                openCaseDetail: 'readonly',
                pendingSchedule: 'writable',
                renderArchiveTable: 'readonly',
                sectionConfigs: 'writable',
                showSaveSuccess: 'readonly',
                submitEvidenceCatalog: 'readonly'
            }
        },
        rules: {
            'strict': 'off',
            'no-unused-vars': ['warn', { 'varsIgnorePattern': '^_' }],
            'no-undef': 'error',
            'no-console': ['warn', { 'allow': ['warn', 'error'] }],
            'no-alert': 'warn',
            'eqeqeq': ['error', 'always'],
            'no-empty': ['error', { 'allowEmptyCatch': true }],
            'no-extra-semi': 'error',
            'semi': ['error', 'always'],
            'no-trailing-spaces': 'error',
            'quotes': ['error', 'single', { 'allowTemplateLiterals': true }],
            'comma-spacing': ['error', { 'before': false, 'after': true }],
            'indent': ['error', 4],
            'max-len': ['warn', { 'code': 150 }],
            'no-redeclare': 'off',
            'no-self-assign': 'error',
            'no-self-compare': 'error',
            'no-unreachable': 'error',
            'no-unsafe-negation': 'error',
            'valid-typeof': 'error'
        }
    }
];
