"""
Marketplace Mock 律师数据 (25 个律师)
覆盖不同专业领域、地区、经验、价格区间
用于前端联调 + 单元测试
"""
from __future__ import annotations

from typing import List
from core.marketplace_engine import LawyerProfile


MOCK_LAWYERS: List[LawyerProfile] = [
    LawyerProfile(
        lawyer_id="L001",
        name="张伟律师",
        firm_id="F-中伦",
        specialties=["contract_dispute", "arbitration", "equity"],
        specialty_depth={"contract_dispute": 180, "arbitration": 95, "equity": 60},
        jurisdictions=["CN"],
        languages=["zh-CN", "en-US"],
        region="北京",
        city="北京市",
        experience_years=12,
        rating=4.8,
        client_review_count=156,
        completed_cases=320,
        win_rate=0.82,
        response_speed_hours=3.5,
        price_per_hour=800,
        price_min=5000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="available",
        bio="中伦律所合伙人, 12年合同与国际仲裁经验, 擅长复杂商业纠纷",
    ),
    LawyerProfile(
        lawyer_id="L002",
        name="李娜律师",
        firm_id="F-金杜",
        specialties=["intellectual_property", "tort", "contract_dispute"],
        specialty_depth={"intellectual_property": 220, "tort": 85, "contract_dispute": 50},
        jurisdictions=["CN", "US"],
        languages=["zh-CN", "en-US"],
        region="上海",
        city="上海市",
        experience_years=9,
        rating=4.5,
        client_review_count=98,
        completed_cases=180,
        win_rate=0.75,
        response_speed_hours=6.0,
        price_per_hour=650,
        price_min=3000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="available",
        bio="金杜律所IP部门, 跨境侵权专家, 处理过多起知名商标侵权案",
    ),
    LawyerProfile(
        lawyer_id="L003",
        name="王建国律师",
        firm_id="F-君合",
        specialties=["equity", "contract_dispute", "arbitration"],
        specialty_depth={"equity": 280, "contract_dispute": 150, "arbitration": 70},
        jurisdictions=["CN", "HK"],
        languages=["zh-CN", "en-US"],
        region="北京",
        city="北京市",
        experience_years=15,
        rating=4.9,
        client_review_count=210,
        completed_cases=450,
        win_rate=0.88,
        response_speed_hours=5.0,
        price_per_hour=1200,
        price_min=10000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="busy",
        bio="君合律所高级合伙人, 公司股权与并购15年经验",
    ),
    LawyerProfile(
        lawyer_id="L004",
        name="陈雪律师",
        firm_id="F-汉坤",
        specialties=["labor_arbitration", "administrative_review", "contract_dispute"],
        specialty_depth={"labor_arbitration": 120, "administrative_review": 65, "contract_dispute": 40},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="广东",
        city="深圳市",
        experience_years=6,
        rating=4.2,
        client_review_count=45,
        completed_cases=90,
        win_rate=0.68,
        response_speed_hours=2.0,
        price_per_hour=400,
        price_min=2000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="汉坤律所, 劳动与行政双领域专家, 响应迅速",
    ),
    LawyerProfile(
        lawyer_id="L005",
        name="赵芳律师",
        firm_id="F-竞天公诚",
        specialties=["family", "tort", "contract_dispute"],
        specialty_depth={"family": 160, "tort": 70, "contract_dispute": 45},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="广东",
        city="广州市",
        experience_years=8,
        rating=4.4,
        client_review_count=76,
        completed_cases=150,
        win_rate=0.72,
        response_speed_hours=4.5,
        price_per_hour=500,
        price_min=3000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="家事与侵权领域8年经验, 擅长调解与诉讼",
    ),
    LawyerProfile(
        lawyer_id="L006",
        name="吴海律师",
        firm_id="F-海问",
        specialties=["cross_border", "arbitration", "contract_dispute", "intellectual_property"],
        specialty_depth={"cross_border": 300, "arbitration": 180, "contract_dispute": 120, "intellectual_property": 80},
        jurisdictions=["CN", "HK", "SG", "US", "ICC", "HKIAC", "SIAC"],
        languages=["zh-CN", "en-US", "bilingual"],
        region="北京",
        city="北京市",
        experience_years=18,
        rating=5.0,
        client_review_count=280,
        completed_cases=600,
        win_rate=0.91,
        response_speed_hours=8.0,
        price_per_hour=1500,
        price_min=15000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="available",
        bio="海问律所高级合伙人, 18年跨境仲裁经验, ICC/HKIAC/SIAC在册仲裁员",
    ),
    LawyerProfile(
        lawyer_id="L007",
        name="孙磊律师",
        firm_id="F-方达",
        specialties=["equity", "contract_dispute", "cross_border"],
        specialty_depth={"equity": 200, "contract_dispute": 150, "cross_border": 90},
        jurisdictions=["CN", "HK", "SG"],
        languages=["zh-CN", "en-US"],
        region="上海",
        city="上海市",
        experience_years=11,
        rating=4.7,
        client_review_count=134,
        completed_cases=260,
        win_rate=0.80,
        response_speed_hours=5.5,
        price_per_hour=950,
        price_min=8000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="busy",
        bio="方达律所, 公司股权与跨境投资专家",
    ),
    LawyerProfile(
        lawyer_id="L008",
        name="周婷律师",
        firm_id="F-中伦",
        specialties=["family", "labor_arbitration", "contract_dispute"],
        specialty_depth={"family": 140, "labor_arbitration": 80, "contract_dispute": 60},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="江苏",
        city="南京市",
        experience_years=7,
        rating=4.3,
        client_review_count=62,
        completed_cases=120,
        win_rate=0.70,
        response_speed_hours=3.0,
        price_per_hour=450,
        price_min=2500,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="中伦南京分所, 家事与劳动法双领域",
    ),
    LawyerProfile(
        lawyer_id="L009",
        name="郑强律师",
        firm_id="F-金杜",
        specialties=["criminal", "tort", "administrative_review"],
        specialty_depth={"criminal": 190, "tort": 70, "administrative_review": 50},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="广东",
        city="深圳市",
        experience_years=14,
        rating=4.6,
        client_review_count=110,
        completed_cases=350,
        win_rate=0.78,
        response_speed_hours=2.5,
        price_per_hour=700,
        price_min=5000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="金杜深圳分所, 刑事辩护专家, 经济犯罪领域经验丰富",
    ),
    LawyerProfile(
        lawyer_id="L010",
        name="吴敏律师",
        firm_id="F-君合",
        specialties=["intellectual_property", "equity", "contract_dispute"],
        specialty_depth={"intellectual_property": 170, "equity": 80, "contract_dispute": 60},
        jurisdictions=["CN", "US"],
        languages=["zh-CN", "en-US"],
        region="北京",
        city="北京市",
        experience_years=10,
        rating=4.6,
        client_review_count=88,
        completed_cases=200,
        win_rate=0.77,
        response_speed_hours=7.0,
        price_per_hour=750,
        price_min=5000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="available",
        bio="君合律所, 知识产权与TMT领域专家",
    ),
    LawyerProfile(
        lawyer_id="L011",
        name="黄伟律师",
        firm_id="F-大成",
        specialties=["contract_dispute", "labor_arbitration", "tort"],
        specialty_depth={"contract_dispute": 100, "labor_arbitration": 65, "tort": 40},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="浙江",
        city="杭州市",
        experience_years=5,
        rating=4.1,
        client_review_count=38,
        completed_cases=80,
        win_rate=0.65,
        response_speed_hours=4.0,
        price_per_hour=350,
        price_min=2000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="大成杭州分所, 民商事诉讼律师",
    ),
    LawyerProfile(
        lawyer_id="L012",
        name="林静律师",
        firm_id="F-盈科",
        specialties=["family", "equity", "contract_dispute"],
        specialty_depth={"family": 110, "equity": 50, "contract_dispute": 70},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="福建",
        city="厦门市",
        experience_years=8,
        rating=4.4,
        client_review_count=70,
        completed_cases=140,
        win_rate=0.73,
        response_speed_hours=5.0,
        price_per_hour=480,
        price_min=3000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="busy",
        bio="盈科厦门分所, 家事与财富传承律师",
    ),
    LawyerProfile(
        lawyer_id="L013",
        name="何峰律师",
        firm_id="F-中伦",
        specialties=["cross_border", "intellectual_property", "arbitration"],
        specialty_depth={"cross_border": 160, "intellectual_property": 130, "arbitration": 70},
        jurisdictions=["CN", "HK", "US", "HKIAC"],
        languages=["zh-CN", "en-US", "bilingual"],
        region="广东",
        city="广州市",
        experience_years=13,
        rating=4.8,
        client_review_count=145,
        completed_cases=290,
        win_rate=0.83,
        response_speed_hours=6.5,
        price_per_hour=1100,
        price_min=8000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="available",
        bio="中伦广州分所, 跨境知识产权诉讼专家",
    ),
    LawyerProfile(
        lawyer_id="L014",
        name="马丽律师",
        firm_id="F-金杜",
        specialties=["labor_arbitration", "family", "contract_dispute"],
        specialty_depth={"labor_arbitration": 150, "family": 90, "contract_dispute": 70},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="四川",
        city="成都市",
        experience_years=9,
        rating=4.5,
        client_review_count=82,
        completed_cases=170,
        win_rate=0.76,
        response_speed_hours=3.5,
        price_per_hour=420,
        price_min=2000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="金杜成都分所, 劳动法专家, 擅长集体劳动争议",
    ),
    LawyerProfile(
        lawyer_id="L015",
        name="龙华律师",
        firm_id="F-海问",
        specialties=["equity", "cross_border", "arbitration", "contract_dispute"],
        specialty_depth={"equity": 220, "cross_border": 150, "arbitration": 100, "contract_dispute": 80},
        jurisdictions=["CN", "HK", "SG", "ICC"],
        languages=["zh-CN", "en-US"],
        region="上海",
        city="上海市",
        experience_years=16,
        rating=4.9,
        client_review_count=195,
        completed_cases=420,
        win_rate=0.86,
        response_speed_hours=10.0,
        price_per_hour=1300,
        price_min=12000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="busy",
        bio="海问上海分所, 跨境并购与国际仲裁专家",
    ),
    LawyerProfile(
        lawyer_id="L016",
        name="谢婷律师",
        firm_id="F-方达",
        specialties=["intellectual_property", "cross_border", "tort"],
        specialty_depth={"intellectual_property": 200, "cross_border": 120, "tort": 60},
        jurisdictions=["CN", "US", "EU"],
        languages=["zh-CN", "en-US"],
        region="北京",
        city="北京市",
        experience_years=10,
        rating=4.7,
        client_review_count=108,
        completed_cases=220,
        win_rate=0.79,
        response_speed_hours=7.5,
        price_per_hour=850,
        price_min=6000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="available",
        bio="方达律所, 跨境知识产权诉讼与许可专家",
    ),
    LawyerProfile(
        lawyer_id="L017",
        name="韩冰律师",
        firm_id="F-大成",
        specialties=["criminal", "contract_dispute", "tort"],
        specialty_depth={"criminal": 160, "contract_dispute": 70, "tort": 55},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="湖北",
        city="武汉市",
        experience_years=12,
        rating=4.5,
        client_review_count=90,
        completed_cases=280,
        win_rate=0.77,
        response_speed_hours=2.0,
        price_per_hour=550,
        price_min=3000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="大成武汉分所, 刑事辩护与民商事交叉领域专家",
    ),
    LawyerProfile(
        lawyer_id="L018",
        name="邓颖律师",
        firm_id="F-盈科",
        specialties=["family", "equity", "labor_arbitration"],
        specialty_depth={"family": 130, "equity": 60, "labor_arbitration": 50},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="湖南",
        city="长沙市",
        experience_years=7,
        rating=4.3,
        client_review_count=55,
        completed_cases=110,
        win_rate=0.71,
        response_speed_hours=4.0,
        price_per_hour=400,
        price_min=2000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="盈科长沙分所, 家事律师, 专注婚姻家庭与财富传承",
    ),
    LawyerProfile(
        lawyer_id="L019",
        name="曹阳律师",
        firm_id="F-君合",
        specialties=["contract_dispute", "arbitration", "equity", "cross_border"],
        specialty_depth={"contract_dispute": 200, "arbitration": 130, "equity": 90, "cross_border": 70},
        jurisdictions=["CN", "HK", "HKIAC"],
        languages=["zh-CN", "en-US"],
        region="广东",
        city="深圳市",
        experience_years=14,
        rating=4.8,
        client_review_count=160,
        completed_cases=340,
        win_rate=0.84,
        response_speed_hours=5.0,
        price_per_hour=1000,
        price_min=8000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="available",
        bio="君合深圳分所, 商事诉讼与仲裁专家",
    ),
    LawyerProfile(
        lawyer_id="L020",
        name="潘红律师",
        firm_id="F-汉坤",
        specialties=["equity", "contract_dispute", "cross_border"],
        specialty_depth={"equity": 180, "contract_dispute": 100, "cross_border": 80},
        jurisdictions=["CN", "SG", "HK"],
        languages=["zh-CN", "en-US"],
        region="上海",
        city="上海市",
        experience_years=11,
        rating=4.6,
        client_review_count=115,
        completed_cases=240,
        win_rate=0.78,
        response_speed_hours=6.0,
        price_per_hour=900,
        price_min=7000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="busy",
        bio="汉坤律所, 私募股权与投融资专家",
    ),
    LawyerProfile(
        lawyer_id="L021",
        name="田宇律师",
        firm_id="F-中伦",
        specialties=["labor_arbitration", "contract_dispute", "social_security"],
        specialty_depth={"labor_arbitration": 200, "contract_dispute": 90, "social_security": 60},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="辽宁",
        city="沈阳市",
        experience_years=13,
        rating=4.6,
        client_review_count=105,
        completed_cases=310,
        win_rate=0.80,
        response_speed_hours=3.0,
        price_per_hour=480,
        price_min=2500,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="中伦沈阳分所, 劳动法专家, 处理过大量群体性劳动争议",
    ),
    LawyerProfile(
        lawyer_id="L022",
        name="董洁律师",
        firm_id="F-金杜",
        specialties=["intellectual_property", "equity", "cross_border"],
        specialty_depth={"intellectual_property": 190, "equity": 70, "cross_border": 100},
        jurisdictions=["CN", "US", "HK"],
        languages=["zh-CN", "en-US", "bilingual"],
        region="江苏",
        city="苏州市",
        experience_years=10,
        rating=4.7,
        client_review_count=95,
        completed_cases=210,
        win_rate=0.81,
        response_speed_hours=5.5,
        price_per_hour=780,
        price_min=5000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="available",
        bio="金杜苏州分所, 知识产权与技术交易专家",
    ),
    LawyerProfile(
        lawyer_id="L023",
        name="袁野律师",
        firm_id="F-大成",
        specialties=["tort", "contract_dispute", "insurance"],
        specialty_depth={"tort": 150, "contract_dispute": 80, "insurance": 60},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="重庆",
        city="重庆市",
        experience_years=9,
        rating=4.4,
        client_review_count=72,
        completed_cases=180,
        win_rate=0.74,
        response_speed_hours=4.5,
        price_per_hour=420,
        price_min=2500,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="大成重庆分所, 人身损害与保险理赔专家",
    ),
    LawyerProfile(
        lawyer_id="L024",
        name="许莉律师",
        firm_id="F-盈科",
        specialties=["family", "tort", "contract_dispute"],
        specialty_depth={"family": 120, "tort": 70, "contract_dispute": 50},
        jurisdictions=["CN"],
        languages=["zh-CN"],
        region="陕西",
        city="西安市",
        experience_years=6,
        rating=4.2,
        client_review_count=40,
        completed_cases=95,
        win_rate=0.67,
        response_speed_hours=5.0,
        price_per_hour=380,
        price_min=2000,
        marketplace_active=True,
        cross_border_capable=False,
        availability="available",
        bio="盈科西安分所, 家事与侵权律师",
    ),
    LawyerProfile(
        lawyer_id="L025",
        name="梁波律师",
        firm_id="F-海问",
        specialties=["cross_border", "arbitration", "equity", "intellectual_property"],
        specialty_depth={"cross_border": 250, "arbitration": 160, "equity": 120, "intellectual_property": 90},
        jurisdictions=["CN", "HK", "SG", "US", "ICC", "HKIAC", "SIAC"],
        languages=["zh-CN", "en-US", "bilingual", "dual_column"],
        region="北京",
        city="北京市",
        experience_years=20,
        rating=5.0,
        client_review_count=310,
        completed_cases=650,
        win_rate=0.93,
        response_speed_hours=12.0,
        price_per_hour=2000,
        price_min=20000,
        marketplace_active=True,
        cross_border_capable=True,
        availability="busy",
        bio="海问律所创始合伙人, 20年跨境争议解决经验, 知名国际仲裁员",
    ),
]


def get_mock_lawyers() -> List[LawyerProfile]:
    """获取 mock 律师列表 (用于前端联调)"""
    return MOCK_LAWYERS.copy()


def get_mock_lawyer_by_id(lawyer_id: str) -> LawyerProfile | None:
    """按 ID 获取 mock 律师"""
    for lawyer in MOCK_LAWYERS:
        if lawyer.lawyer_id == lawyer_id:
            return lawyer
    return None
