[pytest]
asyncio_mode = auto
testpaths = tests
asyncio_default_fixture_loop_scope = function
addopts = --cov=api --cov=core --cov=auth --cov=crawlers --cov-report=term --cov-report=html
filterwarnings =
    ignore::DeprecationWarning:pydantic.*:1
    ignore::DeprecationWarning:fastapi.*:1
