"""拆 script.js: 用函数列表 + 顺序拼接 (非连续)
避免大段切片包含其他模块的代码
"""
import re
from pathlib import Path

ROOT = Path(r'E:\元枢法智前端\yuanxing')
src_file = ROOT / 'assets' / 'js' / 'script.js'
src = src_file.read_text(encoding='utf-8')
lines = src.split('\n')
total = len(lines)

# 找每个 function 起始行
func_re = re.compile(r'^\s*function\s+(\w+)\s*\(', re.MULTILINE)
funcs = {}  # name -> start_line (1-based)
for m in func_re.finditer(src):
    funcs[m.group(1)] = src[:m.start()].count('\n') + 1

# 找每个 function 结束行 (匹配花括号)
def find_func_end(name, start):
    """从 start 行找配对花括号结束行 (1-based, 含)"""
    depth = 0
    seen_open = False
    for i in range(start - 1, total):
        line = lines[i]
        for ch in line:
            if ch == '{':
                depth += 1
                seen_open = True
            elif ch == '}':
                depth -= 1
                if seen_open and depth == 0:
                    return i + 1
    return total

func_end = {n: find_func_end(n, s) for n, s in funcs.items()}

# 模块函数表 (4 modules)
MODULES = {
    'knowledge.js': [
        'applyKnowledgeFilter', 'switchKnowledgeMainTab',
        'startCompile', 'cancelCompile', 'recompile',
        'viewCompileProgress', 'viewWikiPages', 'runLintNow', 'simulateUpload',
    ],
    'ai.js': [
        'switchAITab', 'startNewChat', 'selectHistory', 'filterHistory',
        'switchAIView', 'switchAIViewSubView', 'selectAIHistory', 'filterAIHistory',
        'toggleMoreMenu', 'handleMoreAction',
        'selectExtractSource', 'closeAIExtractModal',
        'startAIExtract', 'copyExtractResult', 'exportExtractResult',
    ],
    'templates.js': [
        'switchTemplateTab', 'fixTemplateViewDOM', 'switchTemplateView',
        'openUploadTemplateModal', 'closeUploadTemplateModal', 'submitUploadTemplate',
        'deletePersonalTemplate', 'openCategoryManageModal', 'closeCategoryManageModal',
        'addCategory', 'sortPersonalTemplates', 'parseTime',
        'updateAllCategoryCount', 'filterPersonalByCategory', 'filterOfficialByCategory',
        'filterOfficialByType', 'applyOfficialFilter', 'clearOfficialSearch',
        'previewOfficialTemplate', 'deleteCategory',
    ],
    'account.js': [
        'toggleNotifications', 'markAllNotifications', 'toggleUserMenu',
        'switchToSubscription', 'toggleBilling', 'showPayment',
        'backToSubscription', 'selectPaymentMethod', 'paySuccess', 'getCurrentPaymentInfo',
        'goToSubscription', 'goToWorkstation', 'switchToOrders', 'switchToMemberCenter',
        'goToMemberCenter', 'switchToAccountSettings',
        'toggleProfileEdit', 'cancelProfileEdit', 'saveProfile', 'showSaveSuccess',
        'addTagInput', 'handleAvatarUpload', 'removeTag', 'showAddTagDialog',
        'removeCertFile', 'toggle2FA', 'showDeviceManager', 'confirmAccountDeletion',
        'autoSaveProfile', 'validateField', 'validateEmail',
        'saveNotificationSettings', 'bindAccount', 'unbindAccount',
    ],
}

# 收集每个模块的函数
module_funcs = {}
for mod, fnames in MODULES.items():
    items = []
    for fname in fnames:
        if fname not in funcs:
            print(f'  WARN: {fname} not found')
            continue
        s = funcs[fname]
        e = func_end[fname]
        items.append((s, e, fname))
    # 按行号排序
    items.sort()
    module_funcs[mod] = items

# 输出统计
print('=== 模块函数块 ===')
for mod, items in module_funcs.items():
    print(f'\n  {mod} ({len(items)} 函数):')
    total_lines = sum(e - s + 1 for s, e, _ in items)
    print(f'    总行数: {total_lines}')
    for s, e, n in items[:6]:
        print(f'    L{s:4d}-L{e:4d} {n} ({e-s+1} 行)')
    if len(items) > 6:
        print(f'    ... +{len(items)-6} more')

# 收集 main.js 保留的函数
all_mod_funcs = set()
for items in module_funcs.values():
    for _, _, n in items:
        all_mod_funcs.add(n)

main_funcs = [(s, e, n) for n, s in funcs.items() if n not in all_mod_funcs]
main_funcs.sort()
print(f'\n  main.js 保留 {len(main_funcs)} 函数:')
total_main = sum(e - s + 1 for s, e, _ in main_funcs)
print(f'    总行数: {total_main}')

# 写文件
def write_module(name, items, header):
    out = ROOT / 'assets' / 'js' / name
    parts = [header, '']
    parts.append('// Auto-generated by module_split.py - DO NOT EDIT IN PLACE')
    parts.append('// Edit the function in its module, then re-run the split script.')
    parts.append('')
    parts.append('(function() {')
    parts.append('    "use strict";')
    parts.append('')
    for s, e, n in items:
        # 取函数体 (s..e 1-based, 包含)
        body = '\n'.join(lines[s-1:e])
        parts.append(body)
        parts.append('')
    parts.append('})();')
    out.write_text('\n'.join(parts), encoding='utf-8')
    print(f'  ✓ {name}: {(out.stat().st_size/1024):.1f} KB')

# 模块 header
HEADERS = {
    'knowledge.js': '''/**
 * 知识库管理模块 - LLM Wiki 风格
 * 包含: 知识库搜索过滤 + 3 Tab 切换 + AI 编译交互
 * 依赖: AppState (main.js)
 */
''',
    'ai.js': '''/**
 * AI 对话模块 - AI 助手 + 历史 + AI 一键提取
 * 包含: AI 标签切换 + 新建对话 + 历史搜索 + 提取要素
 * 依赖: AppState (main.js)
 */
''',
    'templates.js': '''/**
 * 模板管理模块 - 官方模板 + 个人模板
 * 包含: Tab 切换 + 视图切换 + 上传/分类/筛选/排序/预览
 * 依赖: AppState (main.js)
 */
''',
    'account.js': '''/**
 * 账号/会员/支付模块
 * 包含: 通知面板 + 会员订阅 + 支付 + 账号设置 + 个人资料 + 第三方账号
 * 依赖: AppState (main.js)
 */
''',
    'script.js': '''/**
 * LexPrime 主入口 - 案件管理 + 客户 + 日程 + 弹窗 + 路由
 * 拆分模块: knowledge / ai / templates / account (按需加载)
 * 全局状态: AppState + viewCache
 */
''',
}

print('\n=== 写入文件 ===')
for name, items in module_funcs.items():
    write_module(name, items, HEADERS[name])

# main.js 单独写
out = ROOT / 'assets' / 'js' / 'script.js'
parts = [HEADERS['script.js'], '']
parts.append('(function() {')
parts.append('    "use strict";')
parts.append('')

# 顶部全局: L1-L605 一直到 switchView 之前
# 全局: AppState (L1-11), viewCache (L13-?)
# 找 AppState + viewCache 范围
# 用 hard range: 1..605 (前 605 行)
parts.append('    // ===== 全局应用状态 =====')
parts.append('    var AppState = {')
parts.append('        isYearly: false,')
parts.append('        selectedPayment: "alipay",')
parts.append('        selectedDynamicType: "紧急",')
parts.append('        selectedExtractSource: "case",')
parts.append('        batchFiles: [],')
parts.append('        dynamicsViewData: [],')
parts.append('        autoSaveTimer: null,')
parts.append('        dynamicAttachments: []')
parts.append('    };')
parts.append('')
parts.append('    // ===== 视图缓存管理 =====')
parts.append('    var viewCache = {};')
parts.append('')

# 加 main 保留的函数
for s, e, n in main_funcs:
    body = '\n'.join(lines[s-1:e])
    parts.append(body)
    parts.append('')

# 兜底 MutationObserver
parts.append('    // 兜底: 监听 main-content 变化, view-template 出现时立即修')
parts.append('    (function() {')
parts.append('        var main = document.getElementById("main-content");')
parts.append('        if (main) {')
parts.append('            var obs = new MutationObserver(function() {')
parts.append('                if (document.getElementById("view-template")) {')
parts.append('                    setTimeout(tryFix, 30);')
parts.append('                }')
parts.append('            });')
parts.append('            obs.observe(main, { childList: true });')
parts.append('        }')
parts.append('    })();')
parts.append('')  # 闭合 IIFE
parts.append('})();')

out.write_text('\n'.join(parts), encoding='utf-8')
print(f'  ✓ script.js (main): {(out.stat().st_size/1024):.1f} KB')
